### ISSUE TITLE
logs db cannot be created

### ISSUE THREAD

**Issue by klauern** [simonw/llm#138]
Trying to use the `llm` command out of the box.  I created the `io.datasette.llm` directory, but it still creates an error here:

```
☸ ~/Library/Application Support
🕙 17:03:36  ✗  mkdir io.datasette.llm

☸ ~/Library/Application Support
🕙 17:03:44  ➜  llm
test
Sure, feel free to ask a question or give a prompt for me to respond to.
Traceback (most recent call last):
  File "/Users/nklauer/.pyenv/versions/3.11.3/bin/llm", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/nklauer/.local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nklauer/.local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/nklauer/.local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nklauer/.local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nklauer/.local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nklauer/.pyenv/versions/3.11.3/lib/python3.11/site-packages/llm/cli.py", line 258, in prompt
    migrate(db)
  File "/Users/nklauer/.pyenv/versions/3.11.3/lib/python3.11/site-packages/llm/migrations.py", line 14, in migrate
    fn(db)
  File "/Users/nklauer/.pyenv/versions/3.11.3/lib/python3.11/site-packages/llm/migrations.py", line 61, in m003_chat_id_foreign_key
    db["log"].add_foreign_key("chat_id", "log", "id")
  File "/Users/nklauer/.pyenv/versions/3.11.3/lib/python3.11/site-packages/sqlite_utils/db.py", line 2240, in add_foreign_key
    self.db.add_foreign_keys([(self.name, column, other_table, other_column)])
  File "/Users/nklauer/.pyenv/versions/3.11.3/lib/python3.11/site-packages/sqlite_utils/db.py", line 1169, in add_foreign_keys
    cursor.execute(
sqlite3.OperationalError: table sqlite_master may not be modified
```

**Comment by klauern** [comment]
Closing as dupe of #123
