### ISSUE TITLE
llm chat -c fails for API key models

### ISSUE THREAD

**Issue by simonw** [simonw/llm#247]
Running this:
```bash
llm -m 4 'hello'
```
And then:
```bash
llm chat -c
```
Produces this error:
```
Chatting with gpt-4
Type 'exit' or 'quit' to exit
> hi
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/bin/llm", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/llm/cli.py", line 382, in chat
    for chunk in response:
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/llm/models.py", line 91, in __iter__
    for chunk in self.model.execute(
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/llm/default_plugins/openai_models.py", line 271, in execute
    completion = openai.ChatCompletion.create(
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 106, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/openai/api_requestor.py", line 138, in __init__
    self.api_key = key or util.default_api_key()
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
```

**Comment by simonw** [comment]
Relevant code:

https://github.com/simonw/llm/blob/b2fc0a11cf3a353b9e59bcf324a78bbac3b57719/llm/cli.py#L330-L366

For some reason when the conversation is loaded it doesn't end up with the key, whereas when it's created fresh by this code it DOES get the key:

https://github.com/simonw/llm/blob/b2fc0a11cf3a353b9e59bcf324a78bbac3b57719/llm/cli.py#L364C13-L366

**Comment by simonw** [comment]
Here's why:

https://github.com/simonw/llm/blob/b2fc0a11cf3a353b9e59bcf324a78bbac3b57719/llm/cli.py#L330-L335

That's not ensuring that the `model` object with the working API key is made available to that conversation.
