### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int8'

### ISSUE THREAD

**Issue by ituri** [simonw/llm#314]
Hi,

I installed llm using homebrew and get the following error when running it:
```Traceback (most recent call last):
  File "/opt/homebrew/bin/llm", line 5, in <module>
    from llm.cli import cli
  File "/opt/homebrew/Cellar/llm/0.11_1/libexec/lib/python3.12/site-packages/llm/__init__.py", line 16, in <module>
    from .embeddings import Collection
  File "/opt/homebrew/Cellar/llm/0.11_1/libexec/lib/python3.12/site-packages/llm/embeddings.py", line 7, in <module>
    from sqlite_utils import Database
  File "/opt/homebrew/Cellar/llm/0.11_1/libexec/lib/python3.12/site-packages/sqlite_utils/__init__.py", line 4, in <module>
    from .db import Database
  File "/opt/homebrew/Cellar/llm/0.11_1/libexec/lib/python3.12/site-packages/sqlite_utils/db.py", line 207, in <module>
    np.int8: "INTEGER",
    ^^^^^^^
AttributeError: module 'numpy' has no attribute 'int8'
```
What can I do to fix that?

**Comment by ituri** [comment]
Fixed by running `brew link --overwrite numpy`.

**Comment by cmpadden** [comment]
Thanks @ituri! Just for your awareness, @simonw , I also ran into this on a fresh install using `brew install llm`.

```
$ llm
Traceback (most recent call last):
  File "/opt/homebrew/bin/llm", line 5, in <module>
    from llm.cli import cli
  File "/opt/homebrew/Cellar/llm/0.13.1_1/libexec/lib/python3.12/site-packages/llm/__init__.py", line 16, in <module>
    from .embeddings import Collection
  File "/opt/homebrew/Cellar/llm/0.13.1_1/libexec/lib/python3.12/site-packages/llm/embeddings.py", line 7, in <module>
    from sqlite_utils import Database
  File "/opt/homebrew/Cellar/llm/0.13.1_1/libexec/lib/python3.12/site-packages/sqlite_utils/__init__.py", line 4, in <module>
    from .db import Database
  File "/opt/homebrew/Cellar/llm/0.13.1_1/libexec/lib/python3.12/site-packages/sqlite_utils/db.py", line 211, in <module>
    np.int8: "INTEGER",
    ^^^^^^^
AttributeError: module 'numpy' has no attribute 'int8'
```

```
$ brew info llm
==> llm: stable 0.13.1 (bottled)
Access large language models from the command-line
https://llm.datasette.io/
Installed
/opt/homebrew/Cellar/llm/0.13.1_1 (1,135 files, 15MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-04-21 at 21:37:46
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/l/llm.rb
License: Apache-2.0
==> Dependencies
Build: rust ✘
Required: certifi ✔, libyaml ✔, python@3.12 ✔
==> Analytics
install: 931 (30 days), 2,482 (90 days), 8,156 (365 days)
install-on-request: 922 (30 days), 2,466 (90 days), 8,123 (365 days)
build-error: 0 (30 days)
```

```
# macOS version
$ sw_vers -productVersion
14.3
```
