### ISSUE TITLE
Homebrew install error when using 0.12

### ISSUE THREAD

**Issue by alexgw** [simonw/llm#332]
Hi There, 

When updating to 0.12 via Homebrew I get a missing library:

```
llm "hello"
Traceback (most recent call last):
  File "/opt/homebrew/bin/llm", line 5, in <module>
    from llm.cli import cli
  File "/opt/homebrew/Cellar/llm/0.12/libexec/lib/python3.12/site-packages/llm/__init__.py", line 16, in <module>
    from .embeddings import Collection
  File "/opt/homebrew/Cellar/llm/0.12/libexec/lib/python3.12/site-packages/llm/embeddings.py", line 7, in <module>
    from sqlite_utils import Database
  File "/opt/homebrew/Cellar/llm/0.12/libexec/lib/python3.12/site-packages/sqlite_utils/__init__.py", line 1, in <module>
    from .utils import suggest_column_types
  File "/opt/homebrew/Cellar/llm/0.12/libexec/lib/python3.12/site-packages/sqlite_utils/utils.py", line 11, in <module>
    from . import recipes
  File "/opt/homebrew/Cellar/llm/0.12/libexec/lib/python3.12/site-packages/sqlite_utils/recipes.py", line 1, in <module>
    from dateutil import parser
  File "/opt/homebrew/Cellar/llm/0.12/libexec/lib/python3.12/site-packages/dateutil/parser/__init__.py", line 2, in <module>
    from ._parser import parse, parser, parserinfo, ParserError
  File "/opt/homebrew/Cellar/llm/0.12/libexec/lib/python3.12/site-packages/dateutil/parser/_parser.py", line 42, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

On Mac OS 13.3 M2 Pro

I'm not sure if this is to do with my python install but I've been a happy user on this environment up until now!

All the Best,
Alex

**Comment by simonw** [comment]
Likely related:
- https://github.com/dateutil/dateutil/issues/1314

**Comment by simonw** [comment]
Part of the problem here is this I think:

https://github.com/Homebrew/homebrew-core/blob/91168a8372b6bc5e22a7430016153055e628265a/Formula/l/llm.rb#L159

```ruby
  test do
    ENV["OPENAI_API_BASE"] = "https://openai-canned-completion.vercel.app/v1"
    ENV["OPENAI_API_KEY"] = "x"
    assert_match "Hello! How can I assist you today?", shell_output("#{bin}/llm hello --no-log")

    assert_match "llm, version", shell_output("#{bin}/llm --version")
  end
```
Note that it runs that test with `--no-log` - which I think may mean that the test execution for Homebrew doesn't load `sqlite-utils` to the point that the bug is exposed.

**Comment by simonw** [comment]
I'm having trouble replicating this.

Could you try running the following and see if it fixes the problem for you? Knowing one way or the other will help me further debug:

    llm install six

**Comment by alexgw** [comment]
Hey @simonw 

Thanks for the response I get the same error:

```
~ llm install six

Traceback (most recent call last):
  File "/opt/homebrew/bin/llm", line 5, in <module>
    from llm.cli import cli
  File "/opt/homebrew/Cellar/llm/0.12/libexec/lib/python3.12/site-packages/llm/__init__.py", line 16, in <module>
    from .embeddings import Collection
  File "/opt/homebrew/Cellar/llm/0.12/libexec/lib/python3.12/site-packages/llm/embeddings.py", line 7, in <module>
    from sqlite_utils import Database
  File "/opt/homebrew/Cellar/llm/0.12/libexec/lib/python3.12/site-packages/sqlite_utils/__init__.py", line 1, in <module>
    from .utils import suggest_column_types
  File "/opt/homebrew/Cellar/llm/0.12/libexec/lib/python3.12/site-packages/sqlite_utils/utils.py", line 11, in <module>
    from . import recipes
  File "/opt/homebrew/Cellar/llm/0.12/libexec/lib/python3.12/site-packages/sqlite_utils/recipes.py", line 1, in <module>
    from dateutil import parser
  File "/opt/homebrew/Cellar/llm/0.12/libexec/lib/python3.12/site-packages/dateutil/parser/__init__.py", line 2, in <module>
    from ._parser import parse, parser, parserinfo, ParserError
  File "/opt/homebrew/Cellar/llm/0.12/libexec/lib/python3.12/site-packages/dateutil/parser/_parser.py", line 42, in <module>
    import six
ModuleNotFoundError: No module named 'six'

```
If it helps my python settings:

```
which python
/Users/alex/.pyenv/shims/python
____________
pyenv version
3.10.11 (set by /Users/alex/.pyenv/version)
____________
brew --version
Homebrew 4.1.19
```

**Comment by alexgw** [comment]
Just to add I was also able to recreate this on my intel macbook. 

I was able to install via pip so I think it's definitely a homebrew thing.
