### ISSUE TITLE
Last round of manual testing after OpenAI library upgrade

### ISSUE THREAD

**Issue by simonw** [simonw/llm#401]
Following #325, I need to do more manual testing of the OpenAI (and compatible endpoints) features.

Most importantly, I need to test my other plugins that depend on the OpenAI stuff:

- https://github.com/simonw/llm-anyscale-endpoints/blob/main/llm_anyscale_endpoints.py#L2
- https://github.com/simonw/llm-openrouter/blob/main/llm_openrouter.py#L2

I should test that the YAML configuration works against a localhost model too.

**Comment by simonw** [comment]
`llm-anyscale-endpoints` nearly worked:

```
$ llm chat -m codellama/CodeLlama-34b-Instruct-hf
Chatting with codellama/CodeLlama-34b-Instruct-hf
Type 'exit' or 'quit' to exit
Type '!multi' to enter multiple lines, then '!end' to finish
> hi
  Hello! It's nice to meet you. Is there something I can help you with or would you like to chat?Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/llm-p4p8CDpq/lib/python3.10/site-packages/pydantic/main.py", line 726, in __getattr__
    return pydantic_extra[item]
KeyError: 'text'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/llm-p4p8CDpq/bin/llm", line 33, in <module>
    sys.exit(load_entry_point('llm', 'console_scripts', 'llm')())
  File "/Users/simon/.local/share/virtualenvs/llm-p4p8CDpq/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/llm-p4p8CDpq/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/simon/.local/share/virtualenvs/llm-p4p8CDpq/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/simon/.local/share/virtualenvs/llm-p4p8CDpq/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/simon/.local/share/virtualenvs/llm-p4p8CDpq/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/simon/Dropbox/Development/llm/llm/cli.py", line 442, in chat
    for chunk in response:
  File "/Users/simon/Dropbox/Development/llm/llm/models.py", line 91, in __iter__
    for chunk in self.model.execute(
  File "/Users/simon/Dropbox/Development/llm/llm/default_plugins/openai_models.py", line 316, in execute
    response.response_json = remove_dict_none_values(combine_chunks(chunks))
  File "/Users/simon/Dropbox/Development/llm/llm/default_plugins/openai_models.py", line 433, in combine_chunks
    "text": choice.text,
  File "/Users/simon/.local/share/virtualenvs/llm-p4p8CDpq/lib/python3.10/site-packages/pydantic/main.py", line 728, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
AttributeError: 'Choice' object has no attribute 'text'
```
It streamed the answer and then hit an error.

**Comment by simonw** [comment]
In the debugger:
```
(Pdb) list
427  	
428  	    for item in chunks:
429  	        for choice in item.choices:
430  	            if choice.logprobs:
431  	                breakpoint()
432  ->	                logprobs.append(
433  	                    {
434  	                        "text": choice.text,
435  	                        "top_logprobs": choice.logprobs.top_logprobs,
436  	                    }
437  	                )
(Pdb) choice
Choice(delta=ChoiceDelta(content=None, function_call=None, role='assistant', tool_calls=None), finish_reason=None, index=0, logprobs=ChoiceLogprobs(content=[]))
(Pdb) choice.logprobs
ChoiceLogprobs(content=[])
(Pdb) choice.text
*** AttributeError: 'Choice' object has no attribute 'text'
```
Relevant code:

https://github.com/simonw/llm/blob/9119b03a07143c75bf910edd033aa448227a25d2/llm/default_plugins/openai_models.py#L428-L441

**Comment by simonw** [comment]
Found a small fix for that one.

**Comment by simonw** [comment]
I thought this was the fix:
```diff
diff --git a/llm/default_plugins/openai_models.py b/llm/default_plugins/openai_models.py
index b1c66e2..0d6f5fb 100644
--- a/llm/default_plugins/openai_models.py
+++ b/llm/default_plugins/openai_models.py
@@ -428,9 +428,11 @@ def combine_chunks(chunks: List) -> dict:
     for item in chunks:
         for choice in item.choices:
             if choice.logprobs:
+                breakpoint()
+            if choice.logprobs and choice.logprobs.content:
                 logprobs.append(
                     {
-                        "text": choice.text,
+                        "text": choice.text if hasattr(choice, "text") else None,
                         "top_logprobs": choice.logprobs.top_logprobs,
                     }
                 )
```
But got this in a test failure:
```
(Pdb) list
427  	
428  	    for item in chunks:
429  	        for choice in item.choices:
430  	            if choice.logprobs:
431  	                breakpoint()
432  ->	            if choice.logprobs and choice.logprobs.content:
433  	                logprobs.append(
434  	                    {
435  	                        "text": choice.text if hasattr(choice, "text") else None,
436  	                        "top_logprobs": choice.logprobs.top_logprobs,
437  	                    }
(Pdb) choice.logprobs
Logprobs(text_offset=[16], token_logprobs=[-0.6], tokens=['\n\n'], top_logprobs=[{'\n\n': -0.6, '\n': -1.9}])
```

**Comment by simonw** [comment]
Now anypoints says:

>   Hello!Error: 'ChoiceLogprobs' object has no attribute 'top_logprobs'

**Comment by simonw** [comment]
Back to `llm-openrouter`. I think they removed the `headers=` argument: https://github.com/openai/openai-python/discussions/742 mentions `default_headers` now.

Here's my code: https://github.com/simonw/llm-openrouter/blob/45e9ebeba17b0f60176422bd680fc558ad592d46/llm_openrouter.py#L32-L39

```python
        register(
            OpenRouterChat(
                model_id="openrouter/{}".format(model_definition["id"]),
                model_name=model_definition["id"],
                api_base="https://openrouter.ai/api/v1",
                headers={"HTTP-Referer": "https://llm.datasette.io/", "X-Title": "LLM"},
            )
        )
```
That class is a very thin subclass:
```python
from llm.default_plugins.openai_models import Chat

class OpenRouterChat(Chat):
    needs_key = "openrouter"

    def __str__(self):
        return "OpenRouter: {}".format(self.model_id)
```

**Comment by simonw** [comment]
Here's my `headers=` implementation on the `Chat` class:

https://github.com/simonw/llm/blob/0f8ffbfbbd2ebc44e3ca7c1d3ab71fdcad37190e/llm/default_plugins/openai_models.py#L257-L275

Then in `get_client()`:

https://github.com/simonw/llm/blob/0f8ffbfbbd2ebc44e3ca7c1d3ab71fdcad37190e/llm/default_plugins/openai_models.py#L344-L345

**Comment by simonw** [comment]
OK got openrouter working again:
```bash
llm -m openrouter/perplexity/pplx-7b-online 'simon willison hobbies' 
```

> Simon Willison, a co-creator of the Django web framework and an advocate for open-source projects, is known for his diverse interests and hobbies. Some of his hobbies and projects include:
> 
> 1. **Document search tool**: Simon developed an internal document search tool that provides a unified view of the organization's data.
> 
> 2. **Datasette**: He turned his hobby of exploring data into a full-time open-source project, Datasette, an online data exploration and publishing tool for investigative journalists.
> 
> 3. **Prototyping video games**: Simon has recently picked up a new hobby of developing video games using a combination of GPT-3 and DALL-E, creating 60-second prototypes.
> 
> Simon's diverse career has involved a mix of professional work and personal projects, demonstrating his passion for creativity and innovation. You can explore more about his side projects and interests on his website at.
