### ISSUE TITLE
Model installation issue locally

### ISSUE THREAD

**Issue by springcoil** [simonw/llm#430]
Hi @simonw Thanks so much for all the hard work, and this is a fantastic resource. 

There's a possibility I'm doing something wrong but let me try to explain what I see. 

*Problem*
- I was trying to run the mistral model locally on my computer. 
- I use poetry installation of the llm model. 

I get the following errors. 
```llm -m orca-mini-3b-gguf2-q4_0 'difference between a pelican and a walrus'
100%|██████████████████| 1.98G/1.98G [01:33<00:00, 21.2MiB/s]
Error: Unable to instantiate model: Model format not supported (no matching implementation found)```

```

```
llm -m mistral-7b-instruct-v0 'difference between a pelican and a walrus'
Error: Unable to instantiate model: Model format not supported (no matching implementation found)
```
I ran the following. Is it due to the fact that I'm using an M3 chip? 
```
system_profiler SPSoftwareDataType SPHardwareDataType


Software:

    System Software Overview:

      System Version: macOS 14.3 (23D56)
      Kernel Version: Darwin 23.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Peadar’s MacBook Pro
      User Name: User (user)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 31 minutes, 58 seconds

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: Mac15,3
      Model Number: Z1C8000FDB/A
      Chip: Apple M3
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 10151.81.1
      OS Loader Version: 10151.81.1
      Serial Number (system): G6M22DC462
      Hardware UUID: F2514639-4A87-5F30-AA1B-375B3ECB9DEF
      Provisioning UDID: 00008122-001638590881401C
      Activation Lock Status: Disabled
``` 

Hope this helps.

**Comment by dhruvshrma** [comment]
I am running into a similar problem on my M2 Mac as well. The download completes fine but get the following error. 

```
Traceback (most recent call last):
  File "/usr/local/bin/llm", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/Cellar/llm/0.13.1/libexec/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/llm/0.13.1/libexec/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/llm/0.13.1/libexec/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/llm/0.13.1/libexec/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/llm/0.13.1/libexec/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/llm/0.13.1/libexec/lib/python3.12/site-packages/llm/cli.py", line 442, in chat
    for chunk in response:
  File "/usr/local/Cellar/llm/0.13.1/libexec/lib/python3.12/site-packages/llm/models.py", line 91, in __iter__
    for chunk in self.model.execute(
  File "/usr/local/Cellar/llm/0.13.1/libexec/lib/python3.12/site-packages/llm_gpt4all.py", line 157, in execute
    gpt_model = GPT4All(model_name, allow_download=allow_download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/llm/0.13.1/libexec/lib/python3.12/site-packages/gpt4all/gpt4all.py", line 102, in __init__
    self.model = _pyllmodel.LLModel(self.config["path"], n_ctx, ngl)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/llm/0.13.1/libexec/lib/python3.12/site-packages/gpt4all/_pyllmodel.py", line 178, in __init__
    raise ValueError(f"Unable to instantiate model: {'null' if s is None else s.decode()}")
ValueError: Unable to instantiate model: Model format not supported (no matching implementation found)
```
