### ISSUE TITLE
"Model file does not exist" when running `llm models` after installation

### ISSUE THREAD

**Issue by offbyone** [simonw/llm#444]
I just installed `llm`, and tried to run `llm models` which resulted in an exception:

```shellsession
$ pipx install llm
$   installed package llm 0.13.1, installed using Python 3.12.2
  These apps are now globally available
    - llm
done! ✨ 🌟 ✨
$ llm keys set openai
Enter key:
$ llm "Ten fun names for a pet pelican"
1. Squawk
2. ...
$ llm install llm-gpt4all
Collecting llm-gpt4all
... a whole pile of pip
$ llm models
Traceback (most recent call last):
  File "/Users/offby1/.local/bin/llm", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/offby1/.local/pipx/venvs/llm/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/offby1/.local/pipx/venvs/llm/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/offby1/.local/pipx/venvs/llm/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/offby1/.local/pipx/venvs/llm/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/offby1/.local/pipx/venvs/llm/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/offby1/.local/pipx/venvs/llm/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/offby1/.local/pipx/venvs/llm/lib/python3.12/site-packages/llm/cli.py", line 799, in models_list
    for model_with_aliases in get_models_with_aliases():
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/offby1/.local/pipx/venvs/llm/lib/python3.12/site-packages/llm/__init__.py", line 80, in get_models_with_aliases
    pm.hook.register_models(register=register)
  File "/Users/offby1/.local/pipx/venvs/llm/lib/python3.12/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/offby1/.local/pipx/venvs/llm/lib/python3.12/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/offby1/.local/pipx/venvs/llm/lib/python3.12/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/Users/offby1/.local/pipx/venvs/llm/lib/python3.12/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/offby1/.local/pipx/venvs/llm/lib/python3.12/site-packages/llm_gpt4all.py", line 57, in register_models
    models.sort(
  File "/Users/offby1/.local/pipx/venvs/llm/lib/python3.12/site-packages/llm_gpt4all.py", line 59, in <lambda>
    not model.is_installed(),
        ^^^^^^^^^^^^^^^^^^^^
  File "/Users/offby1/.local/pipx/venvs/llm/lib/python3.12/site-packages/llm_gpt4all.py", line 179, in is_installed
    GPT4All.retrieve_model(
  File "/Users/offby1/.local/pipx/venvs/llm/lib/python3.12/site-packages/llm_gpt4all.py", line 38, in retrieve_model
    return _GPT4All.retrieve_model(model_name, model_path, allow_download, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/offby1/.local/pipx/venvs/llm/lib/python3.12/site-packages/gpt4all/gpt4all.py", line 273, in retrieve_model
    raise FileNotFoundError(f"Model file does not exist: {model_dest!r}")
FileNotFoundError: Model file does not exist: PosixPath('/Users/offby1/.cache/gpt4all/mistral-7b-openorca.gguf2.Q4_0.gguf')
```

I'm not sure why; perhaps I need to install a model before listing them?

**Comment by gprime31** [comment]
![2024-03-27_22-15](https://github.com/simonw/llm/assets/44535257/b3e61693-f385-4596-805b-ceeb1ebc5664)

![2024-03-27_20-47](https://github.com/simonw/llm/assets/44535257/f4a07a7c-6c36-4476-9c7a-6f7f6f99e2da)

Just touch the ones you Don't want and download the ones you do... ez fix :)

**Comment by optisynapsis** [comment]
Dear llava-v1.6-34b
Can you convert the filenames in this image to a list

Certainly! Here is the list of filenames from the image:

all-MiniMl-L6-v2-f16.gpt
em_German_mistral_vol.q4.0.gpt
gpt4all-13b-snoopy.q4.0.gpt
gpt4all-13b-newbpe.q4.0.gpt
mistral-13b-instruct.q4.0.gpt
mistral-13b-openorca.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b-newbpe.q4.0.gpt
mistral-13b

**Comment by optisynapsis** [comment]
![Screenshot 2024-03-30 202753](https://github.com/simonw/llm/assets/1255030/566dab88-746f-438f-8972-6a717ec8efa3)

**Comment by optisynapsis** [comment]
I have the same problem. I did try 'touching' the files but it didn't fix the problem for me.

**Comment by FinlandBreakfast** [comment]
> I have the same problem. I did try 'touching' the files but it didn't fix the problem for me.

Same issue

**Comment by cxreiff** [comment]
The proper repository for this issue is simonw/llm-gpt4all- there are already issues opened there for this, e.g. simonw/llm-gpt4all#24. There is a manual code fix, not yet fixed in the repo.

**Comment by offbyone** [comment]
Thanks! I'll close this and follow that.
