### ISSUE TITLE
UTF8 Surrogates Not Allowed

### ISSUE THREAD

**Issue by rsbohn** [simonw/llm#546]
Something in the text returned from GPT 4o can't be logged to the database.

  File "C:\tools\hudson\Lib\site-packages\sqlite_utils\db.py", line 3310, in insert_all
    self.insert_chunk(
  File "C:\tools\hudson\Lib\site-packages\sqlite_utils\db.py", line 3068, in insert_chunk
    result = self.db.execute(query, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\hudson\Lib\site-packages\sqlite_utils\db.py", line 524, in execute
    return self.conn.execute(sql, parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc81' in position 14511: surrogates not allowed

Work around: Disable logs and run the prompt again.

    PS> cat .\transcript.csv | llm -m 4o -s "Extract each place name."

**Comment by AlexanderYastrebov** [comment]
Would be nice to have a small reproducer file.

**Comment by doggy8088** [comment]
I also encountered the same issue, here is how I reproduced it:

```sh
llm 'Use #zh-tw summarize this: $input' --save summarize
curl -s https://llm.datasette.io/en/latest/ | llm -t summarize
```

Here is the result below:

```txt
# LLM 簡介

LLM 是一種命令列工具和 Python 函式庫，用於與大型語言模型互動，支持透過遠端 API 和本地安裝的模型進行操作。它允許使用者從命令列執行提示、 將結果儲存至 SQLite、生成嵌入，並提供擴充功能來支援自我託管的語言模型。

## 快速入門
使用 `pip`、Homebrew 或 `pipx` 安裝 LLM，然後設定 OpenAI API 金鑰即可開始使用。命令示例包括執行提示、擷取圖片文字等。使用者亦可安裝插件 以使用本地模型。

## 特色功能
- 命令列互動
- 支持多種大型模型
- SQLite 日誌記錄
- 嵌入生成

## 參考資源
欲了解更多功能及使用說明，請參考 [官方文件](https://github.com/simonw/llm)。
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\llm.exe\__main__.py", line 7, in <module>
  File "C:\Python312\Lib\site-packages\click\core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\llm\cli.py", line 449, in prompt
    response.log_to_db(db)
  File "C:\Python312\Lib\site-packages\llm\models.py", line 315, in log_to_db
    db["responses"].insert(response)
  File "C:\Python312\Lib\site-packages\sqlite_utils\db.py", line 3219, in insert
    return self.insert_all(
           ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sqlite_utils\db.py", line 3351, in insert_all
    self.insert_chunk(
  File "C:\Python312\Lib\site-packages\sqlite_utils\db.py", line 3109, in insert_chunk
    result = self.db.execute(query, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sqlite_utils\db.py", line 533, in execute
    return self.conn.execute(sql, parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 13798-13800: surrogates not allowed
```
