### ISSUE TITLE
OpenAI plugin should use `self.get_key()`

### ISSUE THREAD

**Issue by simonw** [simonw/llm#552]
The `self.get_key()` mechanism means that Python library users get access to the same persisted API keys as CLI users. Without that anyone using the Python library has to manually set the key themselves. `llm-claude-3` does this correctly, but the default OpenAI plugin does not.

**Comment by simonw** [comment]
Relevant code: https://github.com/simonw/llm/blob/d075336c6900768b664277a7ca7c76a79de9a0cf/llm/default_plugins/openai_models.py#L341-L347

And this method: https://github.com/simonw/llm/blob/d075336c6900768b664277a7ca7c76a79de9a0cf/llm/models.py#L215-L240

**Comment by simonw** [comment]
Before:
```pycon
>>> import llm
>>> print(llm.get_model("gpt-4o-mini").prompt("hi"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/simon/Dropbox/Development/llm/llm/models.py", line 109, in __str__
    return self.text()
  File "/Users/simon/Dropbox/Development/llm/llm/models.py", line 112, in text
    self._force()
  File "/Users/simon/Dropbox/Development/llm/llm/models.py", line 106, in _force
    list(self)
  File "/Users/simon/Dropbox/Development/llm/llm/models.py", line 91, in __iter__
    for chunk in self.model.execute(
  File "/Users/simon/Dropbox/Development/llm/llm/default_plugins/openai_models.py", line 306, in execute
    client = self.get_client()
  File "/Users/simon/Dropbox/Development/llm/llm/default_plugins/openai_models.py", line 352, in get_client
    return openai.OpenAI(**kwargs)
  File "/Users/simon/.local/share/virtualenvs/llm-p4p8CDpq/lib/python3.10/site-packages/openai/_client.py", line 105, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
```

**Comment by simonw** [comment]
After:
```pycon
>>> import llm
>>> print(llm.get_model("gpt-4o-mini").prompt("hi"))
Hello! How can I assist you today?
```
