### ISSUE TITLE
OSError: Windows error 6 (Windows 11)

### ISSUE THREAD

**Issue by rzlodeev** [simonw/llm#578]
There seems to be an issue with "closing" the LLM answer. Traceback:

```> llm chat -m mistral-7b-instruct-v0
Chatting with mistral-7b-instruct-v0
Type 'exit' or 'quit' to exit
Type '!multi' to enter multiple lines, then '!end' to finish
> hi
 Hello! How can I help you today?

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Cockroach\Documents\1PROJECTS\local_llm_test\venv\Scripts\llm.exe\__main__.py", line 7, in <module>
  File "C:\Users\Cockroach\Documents\1PROJECTS\local_llm_test\venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cockroach\Documents\1PROJECTS\local_llm_test\venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Cockroach\Documents\1PROJECTS\local_llm_test\venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cockroach\Documents\1PROJECTS\local_llm_test\venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cockroach\Documents\1PROJECTS\local_llm_test\venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cockroach\Documents\1PROJECTS\local_llm_test\venv\Lib\site-packages\llm\cli.py", line 418, in chat
    prompt = click.prompt("", prompt_suffix="> " if not in_multi else "")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cockroach\Documents\1PROJECTS\local_llm_test\venv\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cockroach\Documents\1PROJECTS\local_llm_test\venv\Lib\site-packages\click\termui.py", line 137, in prompt_func
    echo(text.rstrip(" "), nl=False, err=err)
  File "C:\Users\Cockroach\Documents\1PROJECTS\local_llm_test\venv\Lib\site-packages\click\utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
  File "C:\Users\Cockroach\Documents\1PROJECTS\local_llm_test\venv\Lib\site-packages\click\_compat.py", line 542, in _safe_write
    return _write(s)
           ^^^^^^^^^
  File "C:\Users\Cockroach\Documents\1PROJECTS\local_llm_test\venv\Lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "C:\Users\Cockroach\Documents\1PROJECTS\local_llm_test\venv\Lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "C:\Users\Cockroach\Documents\1PROJECTS\local_llm_test\venv\Lib\site-packages\colorama\ansitowin32.py", line 205, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\Cockroach\Documents\1PROJECTS\local_llm_test\venv\Lib\site-packages\colorama\ansitowin32.py", line 211, in write_plain_text
    self.wrapped.flush()
  File "C:\Users\Cockroach\Documents\1PROJECTS\local_llm_test\venv\Lib\site-packages\click\_winconsole.py", line 177, in write
    raise OSError(self._get_error_message(GetLastError()))
OSError: Windows error 6

**Comment by simonw** [comment]
I've released this as an alpha and `llm-gemini` too - so you can do this:
```bash
alias llm="uvx --with 'llm==0.17a0' --with 'llm-gemini==0.3a0' llm"
```
And then this:
```bash
llm -m gemini-1.5-flash-latest 'how foggy is it on a scale of 1-10, also tell me the current time and date and elevation and vibes' -a 'https://cameras.alertcalifornia.org/public-camera-data/Axis-Purisma1/latest-frame.jpg'
```

> It's not foggy at all.  The fog level is 0. 
> The current time and date is October 28, 2024 at 4:18:12 PM.
> The elevation is 738.
> The vibes are serene and peaceful. The landscape is beautiful with rolling hills and a clear blue sky. The air is probably crisp and fresh.
>
