### ISSUE TITLE
`llm chat` works fine for one followup prompt, then crashes accessing `Response.attachments` (with or without attachments present)

### ISSUE THREAD

**Issue by maxwelljoslyn** [simonw/llm#597]
## Versions
`llm`: 0.17, installed via `pipx`
`llm-claude-3`: 0.6, installed via `llm install`
`llm-gemini`: 0.3, installed via `llm install`
System: MacOS 14.5 (23F79)
Hardware: MBP 14-inch 2021; M1 Pro chip

## Description / Instructions to Reproduce
1. Send an initial prompt with **or without** an attachment, like so: `llm "Describe this photo" -a path/to/photo.jpg`.
	Response comes back fine.
2. Continue the conversation: `llm chat -c`
3. Ask another prompt, e.g. `> Where are animals of this kind located?`
	Response comes back fine.
4. Ask a 3rd prompt, e.g. `> What are other species of this animal?`
5. `llm` crashes with message like so:

```
> What are other species of this animal?
Traceback (most recent call last):
  File "/Users/maxwelljoslyn/.local/bin/llm", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/maxwelljoslyn/.local/pipx/venvs/llm/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxwelljoslyn/.local/pipx/venvs/llm/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/maxwelljoslyn/.local/pipx/venvs/llm/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxwelljoslyn/.local/pipx/venvs/llm/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxwelljoslyn/.local/pipx/venvs/llm/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxwelljoslyn/.local/pipx/venvs/llm/lib/python3.11/site-packages/llm/cli.py", line 535, in chat
    for chunk in response:
  File "/Users/maxwelljoslyn/.local/pipx/venvs/llm/lib/python3.11/site-packages/llm/models.py", line 169, in __iter__
    for chunk in self.model.execute(
  File "/Users/maxwelljoslyn/.local/pipx/venvs/llm/lib/python3.11/site-packages/llm_claude_3.py", line 159, in execute
    "messages": self.build_messages(prompt, conversation),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxwelljoslyn/.local/pipx/venvs/llm/lib/python3.11/site-packages/llm_claude_3.py", line 110, in build_messages
    if response.attachments:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Response' object has no attribute 'attachments'
```

## Notes
Consistently reproducible on my machine with models `claude-3-sonnet` (10/22/2024 version) and `gemini-1.5-pro-latest`. Haven't tried other models.

**Comment by maxwelljoslyn** [comment]
I found out this exact pattern of problem can also happen even without an attachment! Transcript:
```
llm chat -c
Chatting with claude-3-5-sonnet-20241022
Type 'exit' or 'quit' to exit
Type '!multi' to enter multiple lines, then '!end' to finish
> I love updog, do you?
Yes, what's up dog? 😄 

(I see what you did there - trying to get me to ask "what's updog?" Nice try with the classic joke setup!)
> What about downcat, hmm?
Traceback (most recent call last):
  File "/Users/maxwelljoslyn/.local/bin/llm", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/maxwelljoslyn/.local/pipx/venvs/llm/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxwelljoslyn/.local/pipx/venvs/llm/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/maxwelljoslyn/.local/pipx/venvs/llm/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxwelljoslyn/.local/pipx/venvs/llm/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxwelljoslyn/.local/pipx/venvs/llm/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxwelljoslyn/.local/pipx/venvs/llm/lib/python3.11/site-packages/llm/cli.py", line 535, in chat
    for chunk in response:
  File "/Users/maxwelljoslyn/.local/pipx/venvs/llm/lib/python3.11/site-packages/llm/models.py", line 169, in __iter__
    for chunk in self.model.execute(
  File "/Users/maxwelljoslyn/.local/pipx/venvs/llm/lib/python3.11/site-packages/llm_claude_3.py", line 159, in execute
    "messages": self.build_messages(prompt, conversation),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxwelljoslyn/.local/pipx/venvs/llm/lib/python3.11/site-packages/llm_claude_3.py", line 110, in build_messages
    if response.attachments:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Response' object has no attribute 'attachments'
```

**Comment by maxwelljoslyn** [comment]
Update: this is *also* happening when I just start a fresh chat, without using `-c`.

**Comment by maxwelljoslyn** [comment]
For comparison, regular `llm` usage (which I belive by default is calling `llm prompt` under the hood) still works fine with multiple followup messages:
```
$ llm "Help me do a thing"
[response]
$ llm -c "I meant thing A not thing B"
[response]
$ llm -c "Yes, that's right, I'm doing thing A in environment X"
[response]
[etc.]
```

**Comment by maxwelljoslyn** [comment]
Closing since #601 was closed and they were about the same thing.
