### ISSUE TITLE
Unable to install plugins after upgrading to 0.18

### ISSUE THREAD

**Issue by jritsema** [simonw/llm#647]
```sh
llm --version
llm, version 0.18
```

```sh
llm install llm-bedrock-anthropic

Traceback (most recent call last):
  File "/opt/homebrew/bin/llm", line 8, in <module>
    sys.exit(cli())
             ~~~^^
  File "/opt/homebrew/Cellar/llm/0.18/libexec/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/llm/0.18/libexec/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Cellar/llm/0.18/libexec/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/homebrew/Cellar/llm/0.18/libexec/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/llm/0.18/libexec/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/llm/0.18/libexec/lib/python3.13/site-packages/llm/cli.py", line 1271, in install
    run_module("pip", run_name="__main__")
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 222, in run_module
  File "<frozen runpy>", line 142, in _get_module_details
ImportError: No module named pip
```

**Comment by ar-jan** [comment]
I don't know brew, but you could give [uv](https://github.com/astral-sh/uv) a try, e.g.:

> uv python install 3.12
> uv venv --python 3.12
> source .venv/bin/activate
> uv pip install llm

**Comment by jritsema** [comment]
Thanks @ar-jan.  Looks like `uv` doesn't yet support global installs which is what I would want for `llm`.  The joys of python :)
