### ISSUE TITLE
Unable to run llm without getting a `json.decoder.JSONDecoderError`

### ISSUE THREAD

**Issue by datajoely** [simonw/llm#649]
Since this morning I've been unable to run llm inside homebrew or otherwise, is this something on my end? I still have credits left in my OpenAI budget.

Steps to reproduce:

`uvx --isolated --python="3.11" llm`

Stack trace:

```
uvx --isolated --python="3.11" llm
Traceback (most recent call last):
  File "/Users/joel/.cache/uv/archive-v0/erIUMz4YXO991-L48k45-/bin/llm", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/joel/.cache/uv/archive-v0/erIUMz4YXO991-L48k45-/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joel/.cache/uv/archive-v0/erIUMz4YXO991-L48k45-/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/joel/.cache/uv/archive-v0/erIUMz4YXO991-L48k45-/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joel/.cache/uv/archive-v0/erIUMz4YXO991-L48k45-/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joel/.cache/uv/archive-v0/erIUMz4YXO991-L48k45-/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joel/.cache/uv/archive-v0/erIUMz4YXO991-L48k45-/lib/python3.11/site-packages/llm/cli.py", line 353, in prompt
    model.key = get_key(key, model.needs_key, model.key_env_var)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joel/.cache/uv/archive-v0/erIUMz4YXO991-L48k45-/lib/python3.11/site-packages/llm/__init__.py", line 218, in get_key
    stored_keys = load_keys()
                  ^^^^^^^^^^^
  File "/Users/joel/.cache/uv/archive-v0/erIUMz4YXO991-L48k45-/lib/python3.11/site-packages/llm/__init__.py", line 238, in load_keys
    return json.loads(path.read_text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joel/.local/share/uv/python/cpython-3.11.10-macos-aarch64-none/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joel/.local/share/uv/python/cpython-3.11.10-macos-aarch64-none/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joel/.local/share/uv/python/cpython-3.11.10-macos-aarch64-none/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by datajoely** [comment]
The issue was with the `load_keys()` not sure why it suddenly broke, but resetting this fixed it. Perhaps a better error message would be useful.
