### ISSUE TITLE
python API isn't seeing all models

### ISSUE THREAD

**Issue by cleesmith** [simonw/llm#668]
**TL;DR** the **python API** only "knows" about OpenAI models ... none of the: **llm install**'s are seen.

**Installed today, Dec 7, 2024 using:**
```pipx install llm```
**... all works fine.**

**... but after doing:**
```
llm install llm-claude-3
llm install llm-grok
```
**... command line works fine, but neither claude nor grok are seen by the python API ?**

......................................................................
```
(ac) cleesmith:~$ python -B zzz_test_llm.py
import llm
from icecream import ic
ic.configureOutput(includeContext=True, contextAbsPath=True)

# model = llm.get_model("gpt-4o-mini") # this works!
# model = llm.get_model("claude-3-haiku-20240307") # this fails!
model = llm.get_async_model("groq-llama3.1-8b")
# optional, you can configure the key in other ways:
# model.key = "sk-..."
# uses env api keys
response = model.prompt("list planets")
# note: yes, print's have the same results!
ic(response.text())

Traceback (most recent call last):
  File "/opt/miniconda3/envs/ac/lib/python3.10/site-packages/llm/__init__.py", line 187, in get_async_model
    return aliases[name]
KeyError: 'groq-llama3.1-8b'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cleesmith/keypoints/zzz_test_llm.py", line 8, in <module>
    model = llm.get_async_model("groq-llama3.1-8b")
  File "/opt/miniconda3/envs/ac/lib/python3.10/site-packages/llm/__init__.py", line 198, in get_async_model
    raise UnknownModelError("Unknown model: " + name)
llm.UnknownModelError: 'Unknown model: groq-llama3.1-8b'
```

......................................................................
```
(ac) cleesmith:~$ llm models
OpenAI Chat: gpt-4o (aliases: 4o)
OpenAI Chat: gpt-4o-mini (aliases: 4o-mini)
OpenAI Chat: gpt-4o-audio-preview
OpenAI Chat: gpt-3.5-turbo (aliases: 3.5, chatgpt)
OpenAI Chat: gpt-3.5-turbo-16k (aliases: chatgpt-16k, 3.5-16k)
OpenAI Chat: gpt-4 (aliases: 4, gpt4)
OpenAI Chat: gpt-4-32k (aliases: 4-32k)
OpenAI Chat: gpt-4-1106-preview
OpenAI Chat: gpt-4-0125-preview
OpenAI Chat: gpt-4-turbo-2024-04-09
OpenAI Chat: gpt-4-turbo (aliases: gpt-4-turbo-preview, 4-turbo, 4t)
OpenAI Chat: o1-preview
OpenAI Chat: o1-mini
OpenAI Completion: gpt-3.5-turbo-instruct (aliases: 3.5-instruct, chatgpt-instruct)
LLMGroq: groq-llama2
LLMGroq: groq-llama3
LLMGroq: groq-llama3-70b
LLMGroq: groq-llama3.1-8b
LLMGroq: groq-llama3.1-70b
LLMGroq: groq-llama3.1-405b
LLMGroq: groq-mixtral
LLMGroq: groq-gemma
LLMGroq: groq-gemma2
Anthropic Messages: claude-3-opus-20240229
Anthropic Messages: claude-3-opus-latest (aliases: claude-3-opus)
Anthropic Messages: claude-3-sonnet-20240229 (aliases: claude-3-sonnet)
Anthropic Messages: claude-3-haiku-20240307 (aliases: claude-3-haiku)
Anthropic Messages: claude-3-5-sonnet-20240620
Anthropic Messages: claude-3-5-sonnet-20241022
Anthropic Messages: claude-3-5-sonnet-latest (aliases: claude-3.5-sonnet, claude-3.5-sonnet-latest)
Anthropic Messages: claude-3-5-haiku-latest (aliases: claude-3.5-haiku)
... all plugin models are listed by llm command line
```

......................................................................
```
(ac) cleesmith:~$ python -B zzz_test_llm.py
import llm
from icecream import ic
ic.configureOutput(includeContext=True, contextAbsPath=True)
# note: yes, print's have the same results!
for model in llm.get_models():
    ic(model.model_id)
ic('get_async_models')
for model in llm.get_async_models():
    ic(model.model_id)

ic| /Users/cleesmith/keypoints/zzz_test_llm.py:15 in <module>
    model.model_id: 'gpt-4o'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:15 in <module>
    model.model_id: 'gpt-4o-mini'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:15 in <module>
    model.model_id: 'gpt-4o-audio-preview'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:15 in <module>
    model.model_id: 'gpt-3.5-turbo'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:15 in <module>
    model.model_id: 'gpt-3.5-turbo-16k'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:15 in <module>
    model.model_id: 'gpt-4'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:15 in <module>
    model.model_id: 'gpt-4-32k'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:15 in <module>
    model.model_id: 'gpt-4-1106-preview'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:15 in <module>
    model.model_id: 'gpt-4-0125-preview'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:15 in <module>
    model.model_id: 'gpt-4-turbo-2024-04-09'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:15 in <module>
    model.model_id: 'gpt-4-turbo'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:15 in <module>
    model.model_id: 'o1-preview'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:15 in <module>
    model.model_id: 'o1-mini'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:15 in <module>
    model.model_id: 'gpt-3.5-turbo-instruct'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:16 in <module>
    'get_async_models': 'get_async_models'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:18 in <module>
    model.model_id: 'gpt-4o'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:18 in <module>
    model.model_id: 'gpt-4o-mini'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:18 in <module>
    model.model_id: 'gpt-4o-audio-preview'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:18 in <module>
    model.model_id: 'gpt-3.5-turbo'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:18 in <module>
    model.model_id: 'gpt-3.5-turbo-16k'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:18 in <module>
    model.model_id: 'gpt-4'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:18 in <module>
    model.model_id: 'gpt-4-32k'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:18 in <module>
    model.model_id: 'gpt-4-1106-preview'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:18 in <module>
    model.model_id: 'gpt-4-0125-preview'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:18 in <module>
    model.model_id: 'gpt-4-turbo-2024-04-09'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:18 in <module>
    model.model_id: 'gpt-4-turbo'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:18 in <module>
    model.model_id: 'o1-preview'
ic| /Users/cleesmith/keypoints/zzz_test_llm.py:18 in <module>
    model.model_id: 'o1-mini'
```
**... no Claude nor Groq models are listed by python API**

**Comment by cleesmith** [comment]
After uninstalling/removing everything 'llm' due to the pipx install, 
i just did a pip install, turned off off logs, and changed export LLM_USER_PATH=/path/to/my/custom/directory 
... the python api now sees all of the plugins/models and works properly.

Also, how is llm remembering the plugins?

I no longer have:
~/Library/Application Support/io.datasette.llm/
but in my LLM_USER_PATH i see nothing but logs-off ... is the list of plugins stored in lib somewhere?
