### ISSUE TITLE
Listing templates fails with a ValueError if there are no templates

### ISSUE THREAD

**Issue by achabotl** [simonw/llm#80]
I tried listing templates before adding any, to see if there were any built-in ones, but got the following error:

```
=> llm templates list
Traceback (most recent call last):
  File "/Users/achabot/.local/bin/llm", line 8, in <module>
    sys.exit(cli())
  File "/Users/achabot/.local/pipx/venvs/llm/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/achabot/.local/pipx/venvs/llm/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/achabot/.local/pipx/venvs/llm/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/achabot/.local/pipx/venvs/llm/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/achabot/.local/pipx/venvs/llm/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/achabot/.local/pipx/venvs/llm/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/achabot/.local/pipx/venvs/llm/lib/python3.10/site-packages/llm/cli.py", line 303, in templates_list
    max_name_len = max(len(p[0]) for p in pairs)
ValueError: max() arg is an empty sequence
```

The templates directory is empty:

```
=> llm templates path
/Users/achabot/Library/Application Support/io.datasette.llm/templates
=> ls /Users/achabot/Library/Application\ Support/io.datasette.llm/templates/

```

**Comment by simonw** [comment]
This was fixed in:
- https://github.com/simonw/llm/pull/47
