### ISSUE TITLE
Ensure things don't break if you load a conversation from an uninstalled model

### ISSUE THREAD

**Issue by simonw** [simonw/llm#92]
Refs:
- #91 

If someone installs a plugin, logs some responses from it, then uninstalls the plugin, stuff should not break.

**Comment by simonw** [comment]
I tried running a `markov` prompt and then uninstalling `llm-markov` and then running this:
```bash
llm -c hello               
```
Got this error:
```
Traceback (most recent call last):
  File "/Users/simon/Dropbox/Development/llm/llm/__init__.py", line 80, in get_model
    return aliases[name]
KeyError: 'markov'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/llm-p4p8CDpq/bin/llm", line 33, in <module>
    sys.exit(load_entry_point('llm', 'console_scripts', 'llm')())
  File "/Users/simon/.local/share/virtualenvs/llm-p4p8CDpq/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/llm-p4p8CDpq/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/simon/.local/share/virtualenvs/llm-p4p8CDpq/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/simon/.local/share/virtualenvs/llm-p4p8CDpq/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/simon/.local/share/virtualenvs/llm-p4p8CDpq/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/simon/Dropbox/Development/llm/llm/cli.py", line 187, in prompt
    conversation = load_conversation(conversation_id)
  File "/Users/simon/Dropbox/Development/llm/llm/cli.py", line 274, in load_conversation
    conversation = Conversation.from_row(row)
  File "/Users/simon/Dropbox/Development/llm/llm/models.py", line 60, in from_row
    model=get_model(row["model"]),
  File "/Users/simon/Dropbox/Development/llm/llm/__init__.py", line 82, in get_model
    raise UnknownModelError(name)
llm.UnknownModelError: 'markov'
```

**Comment by simonw** [comment]
I think running `llm -c` against a non-existent model should indeed throw an error, just maybe not that noisily.

**Comment by simonw** [comment]
This will do:
```
% llm -c hello
Error: 'Unknown model: markov'
```
